# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40a93136a5199b50af40787bba392decb692f9b1e88b0e3a6fbbbe9813ea992dd122e4246c3a872d75a16893629796b4d8eb2aa3f292b6078acfb4a75355e15c

test:
  secret_key_base: 2494930184d8a6fbffef47b9f844de147dea93f75534b17b46810a5d20486f0971b64eb81904810f56a6237ec4bd49ed4651652ca46fd4c00c78a1aaa7316147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
